stages:
  train:
    cmd: python scripts/train_entry.py ${train.config_path}
    deps:
      - scripts/train_entry.py
      - data/samples/linear.csv
      - configs/base/train_linear.cfg
      - configs/experiments/linear_fast.cfg
      - configs/experiments/linear_long.cfg
    params:
      - train.config_path
    outs:
      - models/checkpoints/linear_model.txt
    metrics:
      - metrics/train_metrics.json

  evaluate:
    cmd: python scripts/evaluate_entry.py ${evaluate.config_path}
    deps:
      - scripts/evaluate_entry.py
      - data/samples/linear.csv
      - configs/base/train_linear.cfg
      - configs/experiments/linear_fast.cfg
      - configs/experiments/linear_long.cfg
      - models/checkpoints/linear_model.txt
    params:
      - evaluate.config_path
    metrics:
      - metrics/eval_metrics.json