# CMake generated Testfile for 
# Source directory: /workspace/tests
# Build directory: /workspace/build-docker/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(smoke_test "/workspace/build-docker/tests/test_smoke")
set_tests_properties(smoke_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;5;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(matrix_test "/workspace/build-docker/tests/test_matrix")
set_tests_properties(matrix_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;11;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(dense_test "/workspace/build-docker/tests/test_dense")
set_tests_properties(dense_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;17;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(activation_test "/workspace/build-docker/tests/test_activation")
set_tests_properties(activation_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;23;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(loss_test "/workspace/build-docker/tests/test_loss")
set_tests_properties(loss_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;29;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(model_test "/workspace/build-docker/tests/test_model")
set_tests_properties(model_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;35;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(training_step_test "/workspace/build-docker/tests/test_training_step")
set_tests_properties(training_step_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;41;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(linear_fit_test "/workspace/build-docker/tests/test_linear_fit")
set_tests_properties(linear_fit_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;47;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(dataset_test "/workspace/build-docker/tests/test_dataset")
set_tests_properties(dataset_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(config_test "/workspace/build-docker/tests/test_config")
set_tests_properties(config_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;61;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(checkpoint_test "/workspace/build-docker/tests/test_checkpoint")
set_tests_properties(checkpoint_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;67;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(evaluate_test "/workspace/build-docker/tests/test_evaluate")
set_tests_properties(evaluate_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;74;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(predict_test "/workspace/build-docker/tests/test_predict")
set_tests_properties(predict_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;81;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(dataset_split_test "/workspace/build-docker/tests/test_dataset_split")
set_tests_properties(dataset_split_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;87;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(normalization_test "/workspace/build-docker/tests/test_normalization")
set_tests_properties(normalization_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;93;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(dataset_multi_test "/workspace/build-docker/tests/test_dataset_multi")
set_tests_properties(dataset_multi_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;100;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(checkpoint_multi_test "/workspace/build-docker/tests/test_checkpoint_multi")
set_tests_properties(checkpoint_multi_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;106;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(predict_multi_test "/workspace/build-docker/tests/test_predict_multi")
set_tests_properties(predict_multi_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;112;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(batch_training_test "/workspace/build-docker/tests/test_batch_training")
set_tests_properties(batch_training_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;118;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(mlp_test "/workspace/build-docker/tests/test_mlp")
set_tests_properties(mlp_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;124;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(mlp_forward_test "/workspace/build-docker/tests/test_mlp_forward")
set_tests_properties(mlp_forward_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;130;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(mlp_train_step_test "/workspace/build-docker/tests/test_mlp_train_step")
set_tests_properties(mlp_train_step_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;136;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(checkpoint_mlp_test "/workspace/build-docker/tests/test_checkpoint_mlp")
set_tests_properties(checkpoint_mlp_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;142;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(hidden_layers_parse_test "/workspace/build-docker/tests/test_hidden_layers_parse")
set_tests_properties(hidden_layers_parse_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;146;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(deep_mlp_test "/workspace/build-docker/tests/test_deep_mlp")
set_tests_properties(deep_mlp_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;150;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(deep_mlp_train_step_test "/workspace/build-docker/tests/test_deep_mlp_train_step")
set_tests_properties(deep_mlp_train_step_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;154;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(checkpoint_deep_mlp_test "/workspace/build-docker/tests/test_checkpoint_deep_mlp")
set_tests_properties(checkpoint_deep_mlp_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;158;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(deep_mlp_forward_test "/workspace/build-docker/tests/test_deep_mlp_forward")
set_tests_properties(deep_mlp_forward_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;162;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(dataset_split_three_way_test "/workspace/build-docker/tests/test_dataset_split_three_way")
set_tests_properties(dataset_split_three_way_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;168;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(eval_empty_dataset_test "/workspace/build-docker/tests/test_eval_empty_dataset")
set_tests_properties(eval_empty_dataset_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;174;add_test;/workspace/tests/CMakeLists.txt;0;")
